### ISSUE TITLE
Memory leak with GLDebugMessageCallback

### ISSUE THREAD

**Issue by seynax** [Onsiea/OnsieaEngine#1]
**Describe the bug**
Memory leak with GLDebugMessageCallback despite running the "free" method to release this callback.

**To Reproduce**
1) Debugging with :
    - java agent, -javaagent:<path>\lwjglx-debug-1.0.0.jar,
    - VM Argument to debugging :  -Dorg.lwjgl.util.DebugStack=true
    - With function in initialization : Configuration.DEBUG_MEMORY_ALLOCATOR.set(true); (see client/fr.onsiea.engine.client.graphics.lwjgl.LWJGLContext [line 52])

2) Start and stop demo application (game/fr.onsiea.engine.game.GameTest.java)

3) See warnings logs
```
[LWJGL] 56 bytes leaked, thread 1 (main), address: 0x1690F7E0250
	at org.lwjgl@3.3.1-snapshot+3/org.lwjgl.system.Callback.create(Callback.java:163)
	at org.lwjgl@3.3.1-snapshot+3/org.lwjgl.system.Callback.<init>(Callback.java:113)
	at org.lwjgl.opengl@3.3.1-snapshot+3/org.lwjgl.opengl.GLDebugMessageCallback.<init>(GLDebugMessageCallback.java:58)
	at OnsieaEngine/fr.onsiea.engine.client.graphics.opengl.OpenGLDebug.<init>(OpenGLDebug.java:12)
	at OnsieaEngine/fr.onsiea.engine.client.graphics.opengl.OpenGLRenderAPIContext.enableDebugging(OpenGLRenderAPIContext.java:426)
	at OnsieaEngine/fr.onsiea.engine.client.graphics.opengl.OpenGLRenderAPIContext.initialization(OpenGLRenderAPIContext.java:248)
	at OnsieaEngine/fr.onsiea.engine.client.graphics.opengl.OpenGLRenderAPIContext.<init>(OpenGLRenderAPIContext.java:240)
	at OnsieaEngine/fr.onsiea.engine.client.graphics.opengl.OpenGLRenderAPIContext.create(OpenGLRenderAPIContext.java:57)
	at OnsieaEngine/fr.onsiea.engine.common.OnsieaGearings.start(OnsieaGearings.java:89)
	at OnsieaEngine/fr.onsiea.engine.common.OnsieaGearings.start(OnsieaGearings.java:69)
	at OnsieaEngine/fr.onsiea.engine.game.GameTest.main(GameTest.java:43)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/30376290/151713999-d39f116b-4b3a-4066-a6a9-d9dd56103fb3.png)

 - OS: Windows
 - Version 10
 - LWJGL lwjgl-nightly-2022-01-22
 - Java 17.0.2

**Comment by seynax** [comment]
**In the process of being resolved.**

**Comment by seynax** [comment]
# OpenGL Debug memory bytes leak correction

- Fixed a memory leak caused by the OpenGL debugger, this was due to bad initialization of OpenGL, two contexts of it had been created
